/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Viet Anh
 */
public class array1_5 extends javax.swing.JFrame {
    
    String [] mang;
    int [] mangint = new int[50];
    /**
     * Creates new form array1_5
     */
    public array1_5() {
        initComponents();
    }
    public void laymang(String a){
        mang = a.replaceAll("\\s", "").split(",");
	for( int i=0;i<mang.length;i++) 
		mangint[i]=Integer.parseInt(mang[i]);
    }
    public String tim (int a[],int n,int t){
        String kq = null;
	kq="";
	for (int i=0;i<n;i++)
		if(a[i]==t) 
			return kq=kq+"Trong mảng có số "+String.valueOf(t);
	return kq=kq+"Trong mảng không có số "+String.valueOf(t);
	
    }
    public static int min(int a[], int n) {
	int m=a[0];
	for (int i=0;i<n;i++)
		if(a[i]<m) m=a[i];
	return m;
    }
    public static int max(int a[], int n) {
	int m=a[0];
	for (int i=0;i<n;i++)
		if(a[i]>m) m=a[i];
	return m;
    }
    public int tong(int a[], int n){
	int s=0;
	for(int i=0;i<n;i++)
		s=s+a[i];
	return s;
}
    public static void Sapxep(int a[],int n) {
	for(int i=0;i<n;i++) 
		for(int j=i+1;j<n;j++) {
			if(a[i]>a[j]) {
				int t=a[i];
				a[i]=a[j];
				a[j]=t;
				}
		}
}   
    public static String kq(int a[],int n) {
	String tam = null;
	 tam="";
	for (int i=0;i<n;i++) {
		if(i<n-1)
		tam=tam+String.valueOf(a[i]+", ");
		else 	tam=tam+String.valueOf(a[i]);
	}
	return tam;
}
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
}
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfmang = new javax.swing.JTextField();
        tftim = new javax.swing.JTextField();
        tim = new javax.swing.JButton();
        tfkq = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        timmax = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        timmin = new javax.swing.JButton();
        tfmang2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sosanh = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tinhtong = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        sapxep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tim.setText("Tìm");
        tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timActionPerformed(evt);
            }
        });

        jLabel1.setText("Nhập mảng");

        jLabel2.setText("Tìm số");

        jLabel3.setText("Kết quả");

        timmax.setText("Tìm");
        timmax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timmaxActionPerformed(evt);
            }
        });

        jLabel4.setText("Số lớn nhất");

        jLabel5.setText("Số nhỏ nhất");

        timmin.setText("Tìm");
        timmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timminActionPerformed(evt);
            }
        });

        jLabel6.setText("Nhập mảng 2");

        sosanh.setText("So sánh ");
        sosanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sosanhActionPerformed(evt);
            }
        });

        jLabel7.setText("So sánh");

        jLabel8.setText("Tính tổng");

        tinhtong.setText("Tính");
        tinhtong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinhtongActionPerformed(evt);
            }
        });

        jLabel9.setText("Sắp xếp");

        sapxep.setText("Sắp xếp");
        sapxep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sapxepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(timmin)
                                    .addComponent(timmax)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(tfmang))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfkq, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sosanh)
                                    .addComponent(tinhtong)
                                    .addComponent(sapxep)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfmang2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tftim, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tim)))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfmang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tftim, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tim)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timmax)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timmin)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfmang2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sosanh))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tinhtong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sapxep)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfkq, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timActionPerformed
        // TODO add your handling code here:
        		try {
				laymang(tfmang.getText());
				}
				catch(NumberFormatException e) {
					tfkq.setText("Nhập lại mảng");
				}
			try {
				tfkq.setText(String.valueOf(tim(mangint,mang.length,Integer.parseInt(tftim.getText()))));
			}
			
			catch(NumberFormatException ex) {
				tfkq.setText("Nhập lại số cần tìm");
			}
    }//GEN-LAST:event_timActionPerformed

    private void timmaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timmaxActionPerformed
        // TODO add your handling code here:
			try {
				laymang(tfmang.getText());
				tfkq.setText(String.valueOf(max(mangint,mang.length)));
			}
			catch(NumberFormatException e) {
				tfkq.setText("Nhập lại mảng");
			}
    }//GEN-LAST:event_timmaxActionPerformed

    private void timminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timminActionPerformed
        // TODO add your handling code here:
                        try {
				laymang(tfmang.getText());
				tfkq.setText(String.valueOf(min(mangint,mang.length)));
			}
			catch(NumberFormatException e) {
				tfkq.setText("Nhập lại mảng");
			}
    }//GEN-LAST:event_timminActionPerformed

    private void sosanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sosanhActionPerformed
        // TODO add your handling code here:
        String kq = null;
        kq ="";
                        try {
				laymang(tfmang.getText());
					}
			catch(NumberFormatException e) {
				tfkq.setText("Nhập lại mảng");
					}
                        String[] mang2 = tfmang2.getText().replaceAll("\\s", "").split(",");
                        for(int i=0;i<mang.length;i++){
                            for(int j=0;i<mang2.length;i++){
                                try{
                                    if(Integer.parseInt(mang2[j])==mangint[i]){
						 kq=kq+mang2[j]+"; ";
                                    }
				tfkq.setText(kq);
                                }
                                catch(NumberFormatException ex) {
					tfkq.setText("Nhập lại mảng 2");
				}
                            }
                        }
    }//GEN-LAST:event_sosanhActionPerformed

    private void tinhtongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinhtongActionPerformed
        // TODO add your handling code here:
                                try {
				laymang(tfmang.getText());
				tfkq.setText(String.valueOf(tong(mangint,mang.length)));
			}
				catch(NumberFormatException e) {
					tfkq.setText("Nhập lại mảng");
				}
    }//GEN-LAST:event_tinhtongActionPerformed

    private void sapxepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sapxepActionPerformed
        // TODO add your handling code here:
        try {
				laymang(tfmang.getText());
				Sapxep(mangint,mang.length);
				tfkq.setText(kq(mangint,mang.length));
			}
				catch(NumberFormatException e) {
					tfkq.setText("");
				}
    }//GEN-LAST:event_sapxepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(array1_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(array1_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(array1_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(array1_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new array1_5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton sapxep;
    private javax.swing.JButton sosanh;
    private javax.swing.JTextField tfkq;
    private javax.swing.JTextField tfmang;
    private javax.swing.JTextField tfmang2;
    private javax.swing.JTextField tftim;
    private javax.swing.JButton tim;
    private javax.swing.JButton timmax;
    private javax.swing.JButton timmin;
    private javax.swing.JButton tinhtong;
    // End of variables declaration//GEN-END:variables

